### ISSUE TITLE
Mention --providers flag on Supported Providers section.

### ISSUE THREAD

**Issue by smola** [src-d/rovers#194]
From @dennwc ([more](https://gist.github.com/dennwc/fc869156bc622c788fbc4bd39baf99dc)):

> There are no mentions how to fetch a single provider. Used my knowledge of Docker to spawn a shell, get help from rovers command, and find the flag.

We do not list all options in README.md, but it would be good to mention that they can be selected with the `--providers` flag in the `Supported Providers` section.

I'll add that `Generate needed API keys for the providers` could be consolidated by moving most of its content to `Supported Providers` and leaving an initial note with a link to the section saying that some providers have additional requirements.

**Comment by mcarmonaa** [comment]
Closed by #200

**Comment by mcarmonaa** [comment]
Closed by #200

**Comment by mcarmonaa** [comment]
Closed by #200
