### ISSUE TITLE
Make docker run commands easier to copy paste

### ISSUE THREAD

**Issue by smola** [src-d/rovers#196]
From @dennwc ([more](https://gist.github.com/dennwc/fc869156bc622c788fbc4bd39baf99dc)):

> Instructions to run the image uses generic names such as postgres. Should be namespaced: rovers_postgres.

This sounds reasonable, since it makes copy-pasting slightly for the users. It is also more consistent than using `postgres` as name in rovers and `some-postgres` in borges, becoming `rovers_postgres` and `borges_postgres`.

**Comment by mcarmonaa** [comment]
Closed by #200 and #199
